stages:
  data_ingestion:
    cmd: python src/pipeline/Training_pipeline.py --task data_ingestion
    deps:
      - src/pipeline/Training_pipeline.py
      - src/constants/constants.py
    outs:
      - artifacts/raw.csv

  data_transformation:
    cmd: python src/pipeline/Training_pipeline.py --task transformation --raw_data_path artifacts/raw.csv
    deps:
      - src/pipeline/Training_pipeline.py
      - src/utilis.py
      - artifacts/raw.csv
    outs:
      - artifacts/X_train.csv
      - artifacts/X_test.csv
      - artifacts/y_train.csv
      - artifacts/y_test.csv
      - artifacts/Processor.pkl
   

  model_training:
    cmd: python src/pipeline/Training_pipeline.py --task model_trainer --x_train_path artifacts/X_train.csv --x_test_path artifacts/X_test.csv 
          --y_train_path artifacts/y_train.csv --y_test_path artifacts/y_test.csv 
    deps:
      - src/pipeline/Training_pipeline.py
      - src/utilis.py
      - artifacts/X_train.csv
      - artifacts/X_test.csv
      - artifacts/y_train.csv
      - artifacts/y_test.csv 
    outs:
      - artifacts/Model.pkl


